version: 2

sources:
  - name: silver
    database: iceberg
    schema: silver
    tables:
      - name: fact_telemetry_event
        description: "Silver long-format telemetry events (Iceberg)."
        columns:
          - name: round_id
            tests:
              - not_null
          - name: course_id
            tests:
              - not_null
          - name: fix_timestamp
            description: "GPS fix timestamp (can be NULL; see is_timestamp_missing)"
          - name: is_timestamp_missing
            description: "True when fix_timestamp is NULL (Silver preserves NULL timestamps)"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "is_timestamp_missing = (fix_timestamp IS NULL)"
          - name: is_location_padding
            description: "True for CSV padding rows where both hole_number and section_number are NULL"
            tests:
              - not_null
          - name: latitude
            tests:
              - dbt_utils.accepted_range:
                  min_value: -90
                  max_value: 90
          - name: longitude
            tests:
              - dbt_utils.accepted_range:
                  min_value: -180
                  max_value: 180

      - name: dim_facility_topology
        description: "Topology definition mapping course sections to physical units."
        columns:
          - name: facility_id
            tests: [not_null]
          - name: unit_id
            tests: [not_null]
          - name: unit_name
          - name: nine_number
          - name: section_start
          - name: section_end

      - name: dim_course_profile
        description: "Human-entered course metadata (seeded)."
        columns:
          - name: course_id
            tests: [not_null]


