version: 2

models:
  - name: fact_rounds
    description: >
      Canonical round fact table (one row per course_id + round_id) built from Silver telemetry.
      This is the preferred upstream for other Gold models so we don't repeatedly scan fix-grain telemetry.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, round_id]
    columns:
      - name: course_id
        tests: [not_null]
      - name: round_id
        tests: [not_null]
      - name: duration_sec
        tests:
          - non_negative
      - name: projected_rate
        tests:
          - between_0_and_100
      - name: problem_rate
        tests:
          - between_0_and_100
      - name: cached_rate
        tests:
          - between_0_and_100
      - name: ts_missing_rate
        tests:
          - between_0_and_100

  - name: pace_summary_by_round
    description: "Round-level pace summary derived from `gold.fact_rounds`."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, round_id]
    columns:
      - name: round_id
        tests: [not_null]
      - name: course_id
        tests: [not_null]
      - name: fix_count
        tests: [non_negative]

  - name: signal_quality_rounds
    description: "Signal quality rates per round (projected/problem) derived from `gold.fact_rounds`."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, round_id]
    columns:
      - name: round_id
        tests: [not_null]
      - name: course_id
        tests: [not_null]
      - name: projected_rate
        tests: [between_0_and_100]
      - name: problem_rate
        tests: [between_0_and_100]

  - name: device_health_errors
    description: "Simple battery-based device health flags derived from telemetry."
    columns:
      - name: round_id
        tests: [not_null]
      - name: course_id
        tests: [not_null]

  - name: dim_course
    description: >
      Course dimension that stitches together configuration, data quality, completeness,
      and observed round ranges. Intended as the main "course info" table for dashboards.
    columns:
      - name: course_id
        tests: [not_null, unique]

  - name: data_quality_overview
    description: >
      Data quality metrics by course. Shows percentage of missing values
      in critical columns and calculates an overall data quality score.
      Use this to identify courses with data collection issues.
    columns:
      - name: course_id
        description: "Unique course identifier"
        tests: [not_null, unique]
      - name: data_quality_score
        description: "0-100 score (higher = better data quality)"
        tests: [between_0_and_100]

  - name: course_configuration_analysis
    description: >
      Analyzes course complexity: 9/18/27 holes, shotgun starts,
      round completion rates, and nine combinations for multi-nine courses.
    columns:
      - name: course_id
        tests: [not_null, unique]
      - name: likely_course_type
        description: "Detected course type: 9-hole, 18-hole, or 27-hole"
      - name: pct_complete
        tests: [between_0_and_100]
      - name: pct_incomplete
        tests: [between_0_and_100]
      - name: pct_nine_hole
        tests: [between_0_and_100]
      - name: pct_full_rounds
        tests: [between_0_and_100]
      - name: pct_shotgun_starts
        tests: [between_0_and_100]

  - name: critical_column_gaps
    description: >
      Prioritized view of missing data by importance tier.
      Tier 1: Pace metrics (essential), Tier 2: Location fields,
      Tier 3: Device health, Tier 4: Round configuration.
      Includes status indicators and recommendations.
    columns:
      - name: course_id
        tests: [not_null, unique]

  - name: fact_round_hole_performance
    description: >
      The most critical analytical table. Granular performance metrics
      aggregated at the hole level (Round + Hole).
      Enriched with topology data (Unit Name) to differentiate loops.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, round_id, hole_number, nine_number]
    columns:
      - name: course_id
        tests: [not_null]
      - name: round_id
        tests: [not_null]
      - name: hole_number
        tests: [not_null]
      - name: nine_number
        description: "1 = First 9 holes played, 2 = Second 9 holes played"
        tests: [not_null]
      - name: course_unit
        description: "Physical unit name (e.g. Red Course, Back Nine)"
      - name: avg_pace_sec
        description: "Average seconds relative to goal (positive = slow)"
      - name: avg_pace_gap_sec
        description: "Average spacing to group ahead (seconds)"
      - name: duration_sec
        tests: [non_negative]

  - name: course_rounds_by_month
    description: >
      Seasonality view: rounds per course per calendar month (based on round start time).
      Includes human-friendly month name for dashboard/demo use and percentage of total rounds.
    columns:
      - name: course_id
        tests: [not_null]
      - name: month_start
        description: >
          Month bucket for the round start timestamp. Rounds with missing timestamps
          are bucketed to a sentinel date (1900-01-01) with month_name = 'Unknown (missing timestamp)'.
        tests: [not_null]
      - name: month_number
      - name: month_name
      - name: rounds
        tests: [non_negative]
      - name: pct_total
        description: "Share of the course’s total rounds that occurred in this month (0–100)."
        tests: [between_0_and_100]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, month_start]

  - name: course_rounds_by_weekday
    description: >
      Seasonality view: rounds per course by weekday (based on round start time).
      Includes human-friendly weekday name for dashboard/demo use.
    columns:
      - name: course_id
        tests: [not_null]
      - name: weekday_number
        description: >
          Day-of-week bucket for the round start timestamp (1-7). Rounds with missing timestamps
          are bucketed to weekday_number = 0 with weekday_name = 'Unknown (missing timestamp)'.
        tests: [not_null]
      - name: weekday_name
      - name: rounds
        tests: [non_negative]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, weekday_number]

  - name: course_start_hole_distribution
    description: >
      Start hole distribution per course. Useful for detecting shotgun starts and validating
      configured start_section vs observed first tee section numbers.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [course_id, start_hole]
    columns:
      - name: course_id
        tests: [not_null]
      - name: start_hole
        tests: [not_null]
      - name: pct_rounds_with_this_start
        tests: [between_0_and_100]
      - name: pct_complete_rounds_with_this_start
        tests: [between_0_and_100]

  - name: telemetry_completeness_summary
    description: >
      Per-course completeness summary of the Silver telemetry table, showing
      how many rows are CSV padding slots (is_location_padding) and how many
      have missing timestamps (is_timestamp_missing). Intended for audits and
      demos rather than filtering.
    columns:
      - name: course_id
        tests: [not_null]
      - name: total_rows
        description: "Total number of Silver rows for this course (including padding)."
      - name: padding_rows
        description: "Rows where is_location_padding = TRUE (CSV padding slots)."
      - name: non_padding_rows
        description: "Rows where is_location_padding = FALSE (real telemetry fixes)."
      - name: ts_missing_rows
        description: "Rows where is_timestamp_missing = TRUE (including padding)."
      - name: ts_missing_non_padding_rows
        description: "Rows where is_timestamp_missing = TRUE AND is_location_padding = FALSE."
      - name: pct_padding_total
        description: "Percentage of total_rows that are padding_rows (0–100)."
        tests: [between_0_and_100]
      - name: pct_ts_missing_total
        description: "Percentage of total_rows with missing timestamps (0–100)."
        tests: [between_0_and_100]
      - name: pct_ts_missing_non_padding
        description: "Percentage of non_padding_rows with missing timestamps (0–100)."
        tests: [between_0_and_100]

  - name: gold_coverage_audit
    description: >
      Per-course audit table that compares core Silver telemetry counts (total,
      padding, timestamp-missing, distinct rounds) against key Gold models
      (fact_rounds, fact_round_hole_performance, seasonality). Designed to make
      any unintentional filtering obvious during demos and validation.
    columns:
      - name: course_id
        tests: [not_null]
      - name: silver_total_rows
      - name: silver_padding_rows
      - name: silver_non_padding_rows
      - name: silver_ts_missing_rows
      - name: silver_ts_missing_non_padding_rows
      - name: silver_distinct_rounds_all
      - name: silver_distinct_rounds_non_padding
      - name: gold_fact_rounds_rows
      - name: gold_fact_rounds_distinct_rounds
      - name: gold_fact_rounds_sum_fix_count
      - name: gold_hole_perf_rows
      - name: gold_hole_perf_distinct_rounds
      - name: gold_hole_perf_distinct_round_hole_nine
      - name: gold_rounds_by_month_sum_rounds
      - name: gold_rounds_by_month_unknown_ts_rounds
      - name: gold_rounds_by_weekday_sum_rounds
      - name: gold_rounds_by_weekday_unknown_ts_rounds
      - name: gold_dim_course_present
      - name: unit_count
