name: tagmarshal_lakehouse
version: "1.0.0"
config-version: 2

profile: tagmarshal_lakehouse

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  tagmarshal_lakehouse:
    +materialized: view
    gold:
      +materialized: table
      +schema: gold


