tagmarshal_lakehouse:
  target: local
  outputs:
    local:
      type: trino
      method: none
      host: trino
      port: 8080
      user: dbt
      catalog: iceberg
      schema: gold
      threads: 4


